name: omnizart
channels:
  - defaults
dependencies:
  - python=3.8
  - pip:
    - vamp>=1.1.0,<2.0.0
    - spleeter>=2.3.0,<3.0.0
    - madmom>=0.16.1,<0.17.0
    - pyfluidsynth>=1.2.5,<2.0.0
    - click>=7.1.2,<8.0.0
    - jsonschema>=3.2.0,<4.0.0
    - librosa>=0.8.0,<0.9.0
    - mir_eval>=0.6,<0.7
    - pillow>=8.3.2,<9.0.0
    - pretty_midi>=0.2.9,<0.3.0
    - pyyaml>=5.3.1,<6.0.0
    - tensorflow==2.5.0
    - tqdm>=4.49.0,<5.0.0
    - urllib3==1.26.4
