[project]
name = "omnizart"
version = "0.6.0"
dynamic = [
    "dependencies",
    "optional-dependencies",
    "requires-python",
    "scripts",
]
description = "Omniscient Mozart, being able to transcribe everything in the music."
readme = "README.md"
authors = [
    { name = "BreezeWhite", email = "miyashita2010@tuta.io" },
    { name = "yjlolo", email = "yjlolo125@gmail.com" },
]
license = { text = "MIT" }
keywords = [
    "automatic music transcription",
    "drum transcription",
    "vocal transcription",
    "beat tracking",
]
classifiers = [
    "Topic :: Multimedia :: Sound/Audio :: MIDI",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Version Control :: Git",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
repository = "https://github.com/Music-and-Culture-Technology-Lab/omnizart"
documentation = "https://music-and-culture-technology-lab.github.io/omnizart-doc/"
homepage = "https://sites.google.com/view/mctl/home"


[tool.poetry.dependencies]
python = ">=3.8,<3.15"
click = ">=7.1.2"
pretty_midi = ">=0.2.9"
librosa = ">=0.8.0"
madmom = ">=0.16.1"
pillow = ">=8.3.2"
pyyaml = ">=5.3.1"
jsonschema = ">=3.2.0"
pyfluidsynth = ">=1.2.5"
vamp = ">=1.1.0"
urllib3 = ">=1.26.4"
spleeter = { version = ">=2.3.0", optional = true }
mir_eval = ">=0.6"
tensorflow = { version = ">=2.5.0", markers = "python_version < '3.14'" }
tf-nightly = { version = "*", markers = "python_version >= '3.14'" }
tf-keras = { version = "*", markers = "python_version >= '3.10'" }
setuptools = "<82"

[tool.poetry.extras]
vocal = ["spleeter"]


[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
pylint = "^2.5.3"
black = "^19.10b0"
numpydoc = "^1.1.0"
yapf = "^0.30.0"
sphinx-press-theme = "^0.5.1"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
sphinx-click = "^2.5.0"
sphinxcontrib-bibtex = "^1.0.0"

[tool.poetry.scripts]
omnizart = 'omnizart.cli.cli:entry'

[tool.black]
line-length = 120
target-version = ['py36']

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
