# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['omnizart',
 'omnizart.cli',
 'omnizart.cli.drum',
 'omnizart.cli.music',
 'omnizart.constants',
 'omnizart.drum',
 'omnizart.feature',
 'omnizart.models',
 'omnizart.music']

package_data = \
{'': ['*']}

install_requires = \
['Cython>=0.29.21,<0.30.0',
 'atari-py>=0.2.6,<0.3.0',
 'click>=7.1.2,<8.0.0',
 'librosa>=0.8.0,<0.9.0',
 'llvmlite>=0.34.0,<0.35.0',
 'madmom>=0.16.1,<0.17.0',
 'opencv-python>=4.4.0,<5.0.0',
 'pretty_midi>=0.2.9,<0.3.0',
 'pyyaml>=5.3.1,<6.0.0',
 'setuptools>=49.6.0,<50.0.0',
 'soundfile>=0.10.3,<0.11.0',
 'tensorflow>=2.3.0,<3.0.0']

entry_points = \
{'console_scripts': ['omnizart = omnizart.cli.cli:entry']}

setup_kwargs = {
    'name': 'omnizart',
    'version': '0.1.0',
    'description': '',
    'long_description': None,
    'author': 'BreezeWhite',
    'author_email': 'freedombluewater@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://sites.google.com/view/mctl/home',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
